language: php
php:
  # Test it in major version and also in hhvm

  - 5.5.9
  - 5.6
  - hhvm
  - 7.0

before_script:
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer install --prefer-source

script: phpunit
